"""delete cascad

Revision ID: c4d9dff70c29
Revises: 19344d7a0d36
Create Date: 2024-12-16 17:23:57.998358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4d9dff70c29'
down_revision: Union[str, None] = '19344d7a0d36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'basket', type_='foreignkey')
    op.drop_constraint(None, 'basket', type_='foreignkey')
    op.create_foreign_key(None, 'basket', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'basket', 'items', ['item_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.create_foreign_key(None, 'items', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    op.alter_column('users', 'tg_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_column('users', 'phone')
    op.drop_column('users', 'location')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=25), nullable=False))
    op.add_column('users', sa.Column('location', sa.VARCHAR(length=50), nullable=False))
    op.add_column('users', sa.Column('phone', sa.VARCHAR(length=12), nullable=False))
    op.alter_column('users', 'tg_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.create_foreign_key(None, 'items', 'categories', ['category_id'], ['id'])
    op.drop_constraint(None, 'basket', type_='foreignkey')
    op.drop_constraint(None, 'basket', type_='foreignkey')
    op.create_foreign_key(None, 'basket', 'items', ['item_id'], ['id'])
    op.create_foreign_key(None, 'basket', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
